export const REQUEST_LOGGIN = 'REQUEST_LOGGIN';
export const SUCCESS_LOGGIN = 'SUCCESS_LOGGIN';
export const FAILED_LOGGIN = 'FAILED_LOGGIN';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILED = 'PROFILE_FAILED';
